### ISSUE TITLE
Have the unit baked into the input field when there's only a single unitOption.

### ISSUE THREAD

**Issue by samturneradha** [aehrc/smart-forms#1056]
**Is your feature request related to a problem? Please describe.**

When using the unitOption extension, a drop-down renders even when there is only a single option available, see below. This appears redundant but is obviously useful for when there are more than one option. 

**Describe the solution you'd like**
I would like there not to be a drop down when there is only a single option for units. 

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://github.com/user-attachments/assets/3baca6c1-9807-417c-a110-2329ed153041)

**Comment by fongsean** [comment]
Hi Sam,

Got this implemented. It's now available in `v1.0.0-alpha.9` along with #1055.

Because these changes are still in the alpha version, Storybook will not have them.


See screenshot below (It's an updated version of [this](https://smartforms.csiro.au/storybook/?path=/story/component-itemtype-quantity--quantity-unit-option-response) story):
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/d46f288a-aa74-4216-be8e-97f7fd86abcd">

Cheers!

**Comment by samturneradha** [comment]
That looks awesome. Can't wait to start using. Thank you :-)
