### ISSUE TITLE
SMART launcher auth token endpoint URL

### ISSUE THREAD

**Issue by dattachandan** [aehrc/smart-forms#350]
While launching the smartform.io from the smarthealthit launcher using provider and patient context, where does the app get the /token from? Why is the app following a Auth code flow (authorisation_code) as well?

![image](https://github.com/aehrc/smart-forms/assets/2154248/5336fdb5-a994-45de-a751-546ded1f2779)

![image](https://github.com/aehrc/smart-forms/assets/2154248/b942a01a-a53d-4d7c-a48b-fc4fd4e11de0)

![image](https://github.com/aehrc/smart-forms/assets/2154248/792c8948-f092-4d3c-af6c-9285d9b4e433)

Also confirming if this is the implemented flow for establishing the provider and patient context? is the /auth token call for this highlighted step?

![image](https://github.com/aehrc/smart-forms/assets/2154248/a2ff21fa-71b9-4876-a1d6-ca4c01f98d91)

**Comment by fongsean** [comment]
Going though the entire launch auth flow step-by-step:
1. Launch
This is the action of clicking on the "Launch" button in the SMART Launcher. It launches the app.

2. Get auth server
The app initially doesn't know the location of the auth server, so it has to request the auth server's endpoint from the CMS server. In this case it is a GET request:
`https://launch.smarthealthit.org/v/r4/fhir/.well-known/smart-configuration`<br>
In the response, auth server endpoint is defined as `https://launch.smarthealthit.org/v/r4/auth`. The app now knows where to go to be authenticated.

3. Request authorisation
Now, since the app knows where to be authenticated, it asks the browser to navigate to the auth server's **authorize** endpoint to get an authorization code. In this case:
`https://launch.smarthealthit.org/v/r4/auth/authorize`<br>
This navigation request consists of all the launch params defined in the first step i.e. client id, scopes, redirect uri, etc. If the auth server accepts this request, it generates an authorization code.

4. Redirect to app
If an authorization code is generated, the user is redirected back to the app with the authorization code. 
Otherwise, you get blocked from proceeding further. A page showing "unauthorised" might be shown along with the reasons why you aren't authorised (possibly due to mismatched scopes or a client id).

5. Token exchange
Now that the app has an authorization code, it performs a POST request to the auth server's **token** endpoint to trade its authorization code for an access token. In this case:
`https://launch.smarthealthit.org/v/r4/auth/token`<br>
This access token can now be used when making requests to the CMS's FHIR API.


Here's where the steps fit In your screenshot:
![image](https://github.com/aehrc/smart-forms/assets/52597778/41e38086-6543-4f2a-8331-f3d1a7cfc523)

Hope that helps.

**Comment by fongsean** [comment]
Hey @dattachandan, are you happy for me to close this issue given it has been stale for a bit?
